In [3]:
import numpy as np

In [5]:
array = np.array([1,2,3,4,5,6])

In [9]:
print(array)

[1 2 3 4 5 6]


In [11]:
print(array[0])

1


In [13]:
print(array[ : 4 ])

[1 2 3 4]


In [19]:
arr1 = array.reshape(3,2,1)

In [21]:
print(arr1)

[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]
